version: '3.3'

networks:
  shared_db:
    external: true

services:
  unit_converter:
    container_name: unit_converter
    image: python:3.11
    build: .
    command: python /usr/src/django_project/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./static/:/tmp/files/
      - .:/usr/src/django_project
    ports:
      - 8000:8000
    env_file:
      - ./.env
