# Generated by Django 4.2.6 on 2023-10-04 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnitConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_unit', models.CharField(blank=None, max_length=20, null=None)),
                ('to_unit', models.CharField(blank=None, max_length=20, null=None)),
                ('conversion', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
            ],
        ),
    ]
